### ISSUE TITLE
Опасно ли?

### ISSUE THREAD

**Issue by deleteBlack666** [AndY2131/OVPN-android-unblocking-vk-mail-yandex#1]
Куда идут запросы?
Безопасно ли использовать?

**Comment by AndY2131** [comment]
Использую свой сервер.
Безопасно, большинство сайтов использует https а значит данные невозможно перехватить. Да и такой цели не преследуется.

**Comment by deleteBlack666** [comment]
> Использую свой сервер.
> Безопасно, большинство сайтов использует https а значит данные невозможно перехватить. Да и такой цели не преследуется.

Хорошо, спасибо за ответ.
