### ISSUE TITLE
ЯндексМузыка

### ISSUE THREAD

**Issue by deleteBlack666** [AndY2131/OVPN-android-unblocking-vk-mail-yandex#2]
Пользуюсь ям вообще не может загрузить главную страницу и прочие разделы кроме моих плейлистов хоть раньше работало.
Через другой впн робит.

**Comment by AndY2131** [comment]
почему то яндекс и вк думают что сервер в финляндии, если не выйдет исправить сменю сервер

**Comment by deleteBlack666** [comment]
> почему то яндекс и вк думают что сервер в финляндии, если не выйдет исправить сменю сервер

Благодарю

**Comment by AndY2131** [comment]
исправлено, сменил хостера

**Comment by deleteBlack666** [comment]
> исправлено, сменил хостера

Хорошо, спасибо
