### ISSUE TITLE
Возможно использовать обход в AdGuard 

### ISSUE THREAD

**Issue by deleteBlack666** [AndY2131/OVPN-android-unblocking-vk-mail-yandex#3]
Здравствуй.
 Можно ли как-то прикрутить чтобы бы в AdGuard работал твой обход?

**Comment by AndY2131** [comment]
adguard сам трафик в впн заворачивает вроде как

**Comment by deleteBlack666** [comment]
> adguard сам трафик в впн заворачивает вроде как

Да но там есть режим прокси

**Comment by AndY2131** [comment]
ну поверх никак, только отключать

**Comment by deleteBlack666** [comment]
Жаль

**Comment by deleteBlack666** [comment]
Кстати успешно завел его) 
Конечно же не с минусами для адгуарда но работает:)
